name: FastAPI Deploy CI/CD

on:
  push:
    branches: 
      - dev

jobs:

  CI:
    runs-on: ubuntu-latest
    environment: production


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt -t python/

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verificar conexión con S3
        run: aws s3 ls

      - name: Create archive of dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          cd dependencies
          zip -r9 $GITHUB_WORKSPACE/python.zip .

      - name: Upload python to S3
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: aws s3 cp python.zip s3://fastapi1243/python.zip

      - name: Update Lambda Layer
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          aws lambda publish-layer-version --layer-name layer_test --content S3Bucket=fastapi1243,S3Key=python.zip

      - name: Create archive of API files
        run: |
          cd $GITHUB_WORKSPACE
          zip -r9 $GITHUB_WORKSPACE/api.zip app

      - name: Verify Zip Content
        run: unzip -l api.zip

      - name: Upload app files to S3
        run: aws s3 cp api.zip s3://fastapi1243/api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    environment: production

    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy new Lambda
        run: |
          set -e
          aws lambda update-function-code --function-name fastapi --s3-bucket fastapi1243 --s3-key api.zip
