name: FastAPI Deploy CI/CD

on:
  push:
    branches: 
      - dev

env:
  S3_BUCKET: fastapi1243
  LAYER_NAME: layer_test
  FUNCTION_NAME: fastapi

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt -t python/

      - name: Install and configure AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Verify S3 connection
        run: aws s3 ls s3://$S3_BUCKET

      - name: Package dependencies
        run: |
          cd python
          zip -r9 $GITHUB_WORKSPACE/python.zip .

      - name: Upload dependencies to S3
        run: aws s3 cp $GITHUB_WORKSPACE/python.zip s3://$S3_BUCKET/python.zip

      - name: Update Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name $LAYER_NAME \
            --content S3Bucket=$S3_BUCKET,S3Key=python.zip

      - name: Package API files
        run: |
          zip -r9 api.zip app

      - name: Verify API Zip Content
        run: unzip -l api.zip

      - name: Upload API files to S3
        run: aws s3 cp api.zip s3://$S3_BUCKET/api.zip

  CD:
    runs-on: ubuntu-latest
    needs: CI
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install and configure AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy new Lambda version
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --s3-bucket $S3_BUCKET \
            --s3-key api.zip
