name: FastAPI Deploy CI/CD

on:
  push:
    branches: 
      - dev

env:
  S3_BUCKET: fastapi1243
  LAYER_NAME: python-libraries
  FUNCTION_NAME: fastapi

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Update Layer and Get ARN
        id: update_layer
        run: |
          # Publica una nueva versión de la capa y obtiene el ARN
          LAYER_VERSION_ARN=$(aws lambda publish-layer-version --layer-name ${{ env.LAYER_NAME }} --zip-file fileb://layer.zip --query 'LayerVersionArn' --output text)
          echo "LAYER_VERSION_ARN=$LAYER_VERSION_ARN" >> $GITHUB_ENV

      - name: Print LAYER_VERSION_ARN
        run: echo "LAYER_VERSION_ARN is ${{ env.LAYER_VERSION_ARN }}"

      # Agrega aquí otros pasos necesarios para tu flujo de trabajo

  CD:
    runs-on: ubuntu-latest
    needs: CI
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if Lambda update is in progress
        run: |
          status=$(aws lambda get-function --function-name $FUNCTION_NAME --query 'Configuration.LastModified' --output text)
          echo "Lambda function last modified: $status"
          # Aquí podrías agregar lógica para verificar si el estado de la función está "en progreso" y esperar si es necesario.

      - name: Deploy new Lambda version
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --s3-bucket $S3_BUCKET \
            --s3-key api.zip

      - name: Update Lambda function with new layer
        run: |
          echo "Using layer ARN: ${{ env.LAYER_VERSION_ARN }}"
          aws lambda update-function-configuration \
            --function-name $FUNCTION_NAME \
            --layers ${{ env.LAYER_VERSION_ARN }}